define({
    selectTaxa: "Sélectionner des taxons",
    selectSpecies: "Sélectionner des espèces",
    reviewSubmitted: "AVIS SOUMIS, le balisage supplémentaire et les commentaires pour cette carte de plage ne sont pas autorisés.",
    rangeVersion: "Gamme Version",
    rangeStage: "Étape",
    rangeScope: "Étendue de la carte de la plage",
    speciesInformation: "Information sur les espèces",
    metadata: "Métadonnées",
    overallFeedback: "Commentaires globaux",
    ecoshapeName: "Écoshape",
    parentEcoregion: "Écorégion parente",
    ecozone: "Écozone",
    terrestrialArea: "Zone terrestre",
    terrestrialProportion: "Proportion terrestre",
    ecoshapePresence: "Présence",
    ecoshapeSpecies: "Espèce",
    multipleEcoshapes: "Plusieurs Écoformes sélectionnées",
    warning: "AVERTISSEMENT",
    warning1: "Le balisage existant pour les Ecoshapes sélectionnés sera remplacé lors de la sauvegarde",
    warning2: "Le balisage choisi ne sera appliqué qu'aux Écoshapes pertinents",
    required: "Obligatoire",
    markup: "Balisage",
    removalReason: "Raison de la suppression",
    removalReason1: "Présumé disparu du pays",
    removalReason2: "Jamais il n'y en a eu",
    removalReason3: "Signalé mais faux",
    removalReason4: "Transitoire/Vagabond",
    removalReason5: "Autre",
    noneSet: "Aucun ensemble",
    comment: "Commentaire",
    reference: "Référence",
    backButton: "Précédent",
    deleteMarkupButton: "Supprimer le balisage",
    saveButton: "Sauvegarder",
    SubmitButton: "Envoyer",
    provideFeedBack: "Veuillez fournir des commentaires sur l’ensemble de la gamme",
    starRating: "Étoiles",
    overallComment: "Commentaire général"
});
